
MVC (Model -View -Controller) 

it is one kind of desing pattern to develop software application we follow some techniques in this pattern which makes us to write by default
a very good programming practise in this .

Model : it is set of domain classes which will act as interface to data which is present behind the application so in this model i
apply business rules means validation i can provide to classes which we have seen in ef using annotations ,this model can be a DAL (data access layer ) means it acts like that ,it is also called a ORM tool
means object realtional mapping toool like linq ,entity framwork so i can keep a entity framewok in model so that i s also possible.

View: user interface which renders the model in the way the user can interact with .so here for one model there can be many views so multiple views may be associiated with a model this is a presental layer we can say .This view is actually a pure html page there will be no code behind file like windows or asp.net it is pure html means only html controls will be there no asp.net controls and no server controls will be there .


Controller : it will recives the request from the user from the view or user interface and after taking taking the request based on type of request  of the user the controller will do modification in databse using the model and after doing the modification the response which it will get will be submitted to end user . it handles complex operations .

 it is one type of class we can say which is having a suffix as controller and in that class some methods which we can action methods are written as per the request .

In controllers two methods we will use more which is get and post 

get means just showing the form is get means just  displaying the form 

for example : insert form in that one form will be shown with text boxex etc and save option button 

post measn after filling the data when u click save button post metod is called 

they will be having same name but one attibute on the top of the function will be there which tells 
whether it is post or get ...
[get]
insertcustomer()
{



}



http://localhost/featured3/index.html

http :yahoo.com /xyz/pqr  in web application it means in yahoo server go the website xyz and in that open page pqr.html 

in mvc 

above url means 

xyz is controller class and pqr is not a html page but it is a function inside a controller class 

class  xyz
{

public return type pqr(23)
{

here logic code u will write in the function 

and u will return some value 

}

}

right now i am interacting by using a url where i specify controlername /actionmetod /paramter going inside the 
method 

i am not providing any link or button to the user so that he can interact with the application 

I am calling a function of controller using a url and and i am seeing a correspnding view generated by controller 

now i will provide a view in that view user will request some thing and based on request the function is called and and its view is executed like that i want to do 


Now open a asp.net core mvc web applciation C# All platforms and web and select asp.net core (Model view controller )
template 

go to home controller add some methods in home controller like this 


 <style>
	table {
		border-collapse: collapse;
		width: 50%;
	}

	table, th, td {
		border: 2px solid black;
	}

	th, td {
		padding: 8px;
		text-align: left;
	}
</style>

<table>
	<thead>
		<tr>
			<th>EmployeeID</th>
			<th>EmpName</th>
			<th>Salary</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>

